### ISSUE TITLE
How to compile and use

### ISSUE THREAD

**Issue by rogerxxxx** [leo-bogert/accuraterip-checksum#4]
Users with little C knowledge will have extreme difficulty, especially if they do not use (or read) the included Eclipse .project .cproject XML files!  Although, you did provide a hint concerning libsndfile. ;-)

**Please add the following to the Readme.md**

To compile with debugging options:
$ CFLAGS="-Og -Wall -g -ggdb" cc -std=c99 -lsndfile accuraterip-checksum.c -o accuraterip-checksum

Example Usage:
$ ./accuraterip-checksum --accuraterip-v2 ~/music-new/Mozart/Essential_Mozart_CD_1/01.Allegro_from_Eine_kleine_Nachtmusik_K525.wav 1 16
9894ED17

**Comment by leo-bogert** [comment]
Fixed by https://github.com/leo-bogert/accuraterip-checksum/commit/bce6d6ec65044c483b758fb85d9858d4365a615c, https://github.com/leo-bogert/accuraterip-checksum/commit/6e2cd02753d412d955957b40dcca9cb863375e2f and https://github.com/leo-bogert/accuraterip-checksum/commit/ec05c42d80874240784f87880ab0d0b5fcfe010c.

Sorry for the long delay and thank you for filing this issue :)

**Comment by leo-bogert** [comment]
Sorry, the above commits made the README wrong, which is fixed by https://github.com/leo-bogert/accuraterip-checksum/commit/e00cfc552d10a74e3488297e4871f36db8f526e4.

**Comment by rogerxxxx** [comment]
LOL!  WOW.  This was sooo long ago, I almost don't even remember typing this!

As they say, better late than never.

Thanks for your time!
